# Generated by Django 4.2.20 on 2025-06-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_project_rename_contactmessage_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("networking", "Networking Mixer"),
                            ("pitch_night", "Pitch Night"),
                            ("panel", "Panel Discussion"),
                            ("workshop", "Workshop"),
                            ("breakfast", "Founders Breakfast"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=300)),
                ("max_attendees", models.IntegerField(default=50)),
                ("registration_url", models.URLField(blank=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="FounderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("fintech", "Fintech"),
                            ("healthtech", "HealthTech"),
                            ("edtech", "EdTech"),
                            ("proptech", "PropTech"),
                            ("deeptech", "DeepTech"),
                            ("saas", "SaaS"),
                            ("ecommerce", "E-commerce"),
                            ("ai_ml", "AI/ML"),
                            ("biotech", "Biotech"),
                            ("cleantech", "CleanTech"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "funding_stage",
                    models.CharField(
                        choices=[
                            ("pre_seed", "Pre-Seed"),
                            ("seed", "Seed"),
                            ("series_a", "Series A"),
                            ("series_b", "Series B+"),
                            ("revenue", "Revenue Stage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("country_origin", models.CharField(max_length=100)),
                ("linkedin_url", models.URLField(blank=True)),
                ("company_website", models.URLField(blank=True)),
                ("pitch_deck_url", models.URLField(blank=True)),
                ("brief_description", models.TextField(max_length=500)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="founder_logos/"
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
