# Generated by Django 4.2.20 on 2025-06-15 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_event_industry_founderprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "investor_type",
                    models.CharField(
                        choices=[
                            ("angel", "Angel Investor"),
                            ("vc", "Venture Capital"),
                            ("family_office", "Family Office"),
                            ("corporate", "Corporate VC"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "min_investment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_investment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("bio", models.TextField(max_length=500)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("focus_industries", models.ManyToManyField(to="core.industry")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.DeleteModel(
            name="Testimonial",
        ),
    ]
